### ISSUE TITLE
wrong .zip link on the seeedstudio getting started for Grove Vision AI V2

### ISSUE THREAD

**Issue by hpssjellis** [Seeed-Studio/ModelAssistant#176]
@LynnL4 

If you go to this link  

https://wiki.seeedstudio.com/grove_vision_ai_v2/

and go about 6 pages down and find the line that says 

```Windows CDC driver: CH343CDC.ZIP```

it actually loads the other .zip file and should load this .zip file

https://files.seeedstudio.com/wiki/grove-vision-ai-v2/res/CH343CDC.ZIP

P.S I just got 2 Grove Vision AI V2 boards. I thought they were not working, but the USB-C cable takes a fair bit of force to plug in properly until you can hear the click.  All is working great, what a great board.

**Comment by LynnL4** [comment]
Thanks for the reminder. I've already , ,I've submitted a fix

https://github.com/Seeed-Studio/wiki-documents/pull/1007
