### ISSUE TITLE
Is  ModelAssistant still support ESP32-S3-EYE?

### ISSUE THREAD

**Issue by kyleaitgroup** [Seeed-Studio/ModelAssistant#198]
I followed the procedures outlined in SSCMA and Edgelab to train and deploy FOMO. I noticed that the current deployment method is through SenseCraft-Web-Toolkit. Does this mean that the current version no longer supports ESP32-S3-EYE?

**Comment by Pillar1989** [comment]
@kyleaitgroup  Yes, We support the ESP32-S3 chip, and SenseCraft-Web-Toolkit is just a simple way to deploy it.
