### ISSUE TITLE
Instructions for installing on Windows are outdated or wrong. Multiple errors compiling mmcv.

### ISSUE THREAD

**Issue by djairjr** [Seeed-Studio/ModelAssistant#233]
**Describe the bug**
Unable to install following the steps indicated in the link: https://sensecraftma.seeed.cc/introduction/installation

For Windows 11, Miniconda, Pytorch.

Unable to install MMCV-full returns multiple compilation errors.

**Environment**
Environment you use when bug appears:

1. Python version - 3.8.19
2. PyTorch Version - '2.3.1'
3. MMCV Version - '2.2.0' # Not installing via mim as indicated. Installed with MMCV site instructions...
4. EdgeLab Version
5. Code you run - Following this exact instructions for Windows 11 with Anaconda.
6. The detailed error
 Could not build wheels for mmcv-full, mmcv, which is required to install pyproject.toml-based projects

**Additional context**

**Comment by Pillar1989** [comment]
@djairjr  Sorry, we rarely develop models and algorithms on Windows, we suggest you choose Linux or MacOS, Google Colab is also a good choice.Regarding the use of mmcv on Windows, I hope the following link can help you.
https://mmcv.readthedocs.io/en/latest/get_started/installation.html
