### ISSUE TITLE
Urgent help needed

### ISSUE THREAD

**Issue by bhanu5125** [Seeed-Studio/ModelAssistant#238]
**I want TEXT EXTRACTION USING SSCMA**

Please help

**Comment by Pillar1989** [comment]
@bhanu5125 What kind of need is that? Can you describe it in detail?

**Comment by bhanu5125** [comment]
For my clg project submittion I want text extration from image using sscma

**Comment by baorepo** [comment]
I see that you have not responded for a long time, I will close this issue first, if you have new developments, we will open this issue.
